# Generated by Django 4.0.1 on 2022-05-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='疾病名称')),
            ],
            options={
                'verbose_name_plural': '疾病种类',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_uid', models.CharField(max_length=30, unique=True, verbose_name='微信号')),
                ('userName', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(0, '女性'), (1, '男性')], default=1, verbose_name='性别')),
                ('phone_number', models.CharField(max_length=20, verbose_name='电话号码')),
                ('occupation', models.CharField(max_length=30, verbose_name='职业')),
            ],
            options={
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(verbose_name='身高')),
                ('GI', models.FloatField(verbose_name='血糖指数')),
                ('cholesterol', models.FloatField(verbose_name='胆固醇')),
                ('UA', models.FloatField(verbose_name='尿酸指数')),
                ('BP', models.FloatField(verbose_name='血压')),
                ('illness', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserInfo.illnessmode', verbose_name='疾病名称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserInfo.userinfo', verbose_name='用户信息')),
            ],
            options={
                'verbose_name_plural': '健康档案',
            },
        ),
    ]
