# Generated by Django 4.0.1 on 2022-05-03 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EAR', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='平均需要量')),
                ('RNI', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='推荐摄入量')),
                ('AI', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='适宜摄入量')),
                ('AMDR', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='宏量元素可接受范围')),
                ('UL', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='可耐受最高摄入量')),
            ],
            options={
                'verbose_name_plural': '营养摄入标准',
            },
        ),
    ]
