# Generated by Django 4.0.1 on 2022-05-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_EER', to='Food.standard', verbose_name='能量需要量')),
                ('VA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VA', to='Food.standard', verbose_name='维生素A')),
                ('VB1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VB1', to='Food.standard', verbose_name='维生素B1')),
                ('VB12', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VB12', to='Food.standard', verbose_name='维生素B12')),
                ('VB2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VB2', to='Food.standard', verbose_name='维生素B2')),
                ('VB3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VB3', to='Food.standard', verbose_name='烟酸')),
                ('VB5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VB5', to='Food.standard', verbose_name='泛酸')),
                ('VB6', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VB6', to='Food.standard', verbose_name='维生素B6')),
                ('VB9', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VB9', to='Food.standard', verbose_name='叶酸')),
                ('VC', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VC', to='Food.standard', verbose_name='维生素C')),
                ('VD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VD', to='Food.standard', verbose_name='维生素D')),
                ('VE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VE', to='Food.standard', verbose_name='维生素E')),
                ('VK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_VK', to='Food.standard', verbose_name='维生素K')),
                ('biotin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_biotin', to='Food.standard', verbose_name='生物素')),
                ('calcium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_calcium', to='Food.standard', verbose_name='钙')),
                ('carbohydrate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_carbohydrate', to='Food.standard', verbose_name='碳水化合物')),
                ('chlorine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_chlorine', to='Food.standard', verbose_name='氯')),
                ('choline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_choline', to='Food.standard', verbose_name='胆碱')),
                ('chromium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_chromium', to='Food.standard', verbose_name='铬')),
                ('copper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_copper', to='Food.standard', verbose_name='铜')),
                ('fat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_fat', to='Food.standard', verbose_name='脂肪')),
                ('iodine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_iodine', to='Food.standard', verbose_name='碘')),
                ('iron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_iron', to='Food.standard', verbose_name='铁')),
                ('kalium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_kalium', to='Food.standard', verbose_name='钾')),
                ('magnesium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_magnesium', to='Food.standard', verbose_name='镁')),
                ('molybdenum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_molybdenum', to='Food.standard', verbose_name='钼')),
                ('niacinamide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_niacinamide', to='Food.standard', verbose_name='烟酰胺')),
                ('phosphorus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_phosphorus', to='Food.standard', verbose_name='磷')),
                ('protein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_protein', to='Food.standard', verbose_name='蛋白质')),
                ('selenium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_selenium', to='Food.standard', verbose_name='硒')),
                ('sodium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_sodium', to='Food.standard', verbose_name='钠')),
                ('zinc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_zinc', to='Food.standard', verbose_name='锌')),
            ],
            options={
                'verbose_name_plural': '人体所需营养',
            },
        ),
    ]
