# Generated by Django 4.0.1 on 2022-05-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
            preserve_default=False,
        ),
    ]
