# Generated by Django 4.0.1 on 2022-05-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_standard_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeInfo', models.CharField(max_length=20, verbose_name='类别')),
            ],
            options={
                'verbose_name_plural': '营养种类',
            },
        ),
        migrations.RemoveField(
            model_name='standard',
            name='age',
        ),
    ]
