# Generated by Django 4.0.1 on 2022-05-03 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_remove_nutrition_eer_remove_nutrition_va_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='TypeInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Food.nuttype', verbose_name='类别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='nid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Food.nutrition', verbose_name='营养'),
            preserve_default=False,
        ),
    ]
