# Generated by Django 4.0.1 on 2022-05-04 04:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0006_remove_nutrition_eer_remove_nutrition_va_and_more'),
    ]

    operations = [
        
    ]
