# Generated by Django 4.0.1 on 2022-05-04 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0007_remove_nutrition_eer_remove_nutrition_va_and_more'),
    ]

    operations = [
        
    ]
