# Generated by Django 4.0.1 on 2022-05-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0010_remove_standard_nid_nutrition_age_standard_ageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField(verbose_name='含量')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.nuttype', verbose_name='成分')),
            ],
        ),
    ]
