# Generated by Django 4.0.1 on 2022-05-05 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0011_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='食物名字')),
                ('type', models.SmallIntegerField(choices=[(0, '水果'), (1, '蔬菜'), (2, '豆类'), (3, '面食'), (4, '奶制品'), (5, '肉类'), (6, '油、脂肪')], verbose_name='食品类型')),
                ('img', models.ImageField(null=True, upload_to='img/', verbose_name='食物图片')),
                ('effect', models.CharField(max_length=100, verbose_name='功效')),
                ('taboo', models.CharField(max_length=100, verbose_name='禁忌')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.composition', verbose_name='营养成分')),
            ],
        ),
    ]
