# Generated by Django 4.0.1 on 2022-05-05 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0012_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='composition',
        ),
        migrations.AddField(
            model_name='composition',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Food.food', verbose_name='食物'),
            preserve_default=False,
        ),
    ]
