# Generated by Django 4.0.1 on 2022-05-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0013_remove_food_composition_composition_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name_plural': '食物营养成分'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': '食物信息'},
        ),
    ]
